# This is file is used by Kamal.
service: kamal-test

image: brijathom/kamal-test

servers:
  web:
    - 172.205.225.21

proxy:
  ssl: false
  host: kamal-target-test.westeurope.cloudapp.azure.com
  app_port: 8080
  healthcheck:
    path: /

registry:
  username: brijathom
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: kamal
  keys: [ "~/.ssh/backend-test" ]

accessories:
  postgres:
    image: postgres:16
    host: 172.205.225.21
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: productdb
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/production_setup.sql:/docker-entrypoint-initdb.d/setup.sql